export enum TrainingCategories {
    BUSINESS = 'BUSINESS',
    FINANCE = 'FINANCE',
    OFFICE_PRODUCTIVITY = 'OFFICE_PRODUCTIVITY',
    PROGRAMMING = 'PROGRAMMING',
    PERSONAL_DEVELOPMENT = 'PERSONAL_DEVELOPMENT',
    DESIGN = 'DESIGN',
    MARKETING = 'MARKETING',
    TEACHING_ACADEMICS = 'TEACHING_ACADEMICS'
}